import { useState } from "react";
import Head from "next/head";

const to = "test@test.de";
const subject = `email test `;
const body = `
Hello,
Whats up ÜüÄä

Bye


PS:`;

const createMailTo = (returns: string, index: number) => {
  let url = `mailto:${to}?subject=${encodeURI(`${subject} #${index + 1}`)}`;
  if (body != null) {
    url = `${url}&body=${encodeURI(replaceReturns(body, returns))}`;
  }
  return url;
};

const replaceReturns = (value: string, returns: string) => {
  return value.replace(/\n/g, returns);
};

const createLink = (raw: string, returns: string, index: number) => {
  return (
    <a href={createMailTo(returns, index)}>
      <code>{raw}</code>
      {" -> "}
      <code>{encodeURI(returns)}</code>
    </a>
  );
};

export default function Home() {
  const [customLink, setCustomLink] = useState("");

  return (
    <html>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css"
        />
      </Head>

      <body>
        <main>
          <h1>
            The <code>mailto:</code> link tester
          </h1>
          <h2>Links</h2>
          <ol>
            {[
              ["\\n", "\n"],
              ["\\r\\n", "\r\n"],
              ["<br>", "<br>"],
            ].map(([raw, returns], index) => (
              <li>{createLink(raw, returns, index)}</li>
            ))}
          </ol>
          <h2>How it is supposed to look</h2>
          <h3>To</h3>
          <pre>
            <code>{to}</code>
          </pre>
          <h3>Subject</h3>
          <pre>
            <code>{subject} #1</code>
          </pre>
          <h3>Body</h3>
          <pre>
            <code>{body}</code>
          </pre>
          <h2>Bring your own link</h2>

          <p>
            Goto <a href="https://mailtolink.me/">mailtolink.me</a> and copy
            your link
          </p>
          <div>
            <input
              onChange={(e) => setCustomLink(e.target.value)}
              value={customLink}
              type="text"
              name="mailto"
              id="custom_mailto"
              placeholder="mailto:..."
            />
            <a href={customLink}>{"--> Your link <-- "}</a>
          </div>
        </main>
      </body>
    </html>
  );
}
