import Head from "next/head";

const to = "test@test.de";
const subject = `email test `;
const body = `
Hello,

Bye


PS:`;

const createMailTo = (returns: string, index: number) => {
  let url = `mailto:${to}?subject=${encodeURI(`${subject} #${index + 1}`)}`;
  if (body != null) {
    url = `${url}&body=${encodeURI(replaceReturns(body, returns))}`;
  }
  return url;
};

const replaceReturns = (value: string, returns: string) => {
  return value.replace(/\n/g, returns);
};

const createLink = (raw: string, returns: string, index: number) => {
  return (
    <li>
      <a href={createMailTo(returns, index)}>
        <code>{raw}</code>
        {" -> "}
        <code>{encodeURI(returns)}</code>
      </a>
    </li>
  );
};

export default function Home() {
  return (
    <html>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css"
        />
      </Head>

      <body>
        <main>
          <h1>
            The <code>mailto:</code> link tester
          </h1>
          <h2>Links</h2>
          <ol>
            {[
              ["\\n", "\n"],
              ["\\r\\n", "\r\n"],
              ["<br>", "<br>"],
            ].map(([raw, returns], index) => createLink(raw, returns, index))}
          </ol>
          <h2>How it is supposed to look</h2>

          <h3>To</h3>
          <pre>
            <code>{to}</code>
          </pre>
          <h3>Subject</h3>
          <pre>
            <code>{subject} #1</code>
          </pre>
          <h3>Body</h3>
          <pre>
            <code>{body}</code>
          </pre>
        </main>
      </body>
    </html>
  );
}
